on:
  push:
    branches:
      - cicd

jobs:
  my-jobs:
    runs-on: ubuntu-latest
    container:
      image: rocker/r2u:22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: list files
        run: ls -lah
      - name: install-r
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.1'
